### PR TITLE
Add compatibility with PHP 8

### PR DESCRIPTION
**Pull request by ausi**

### CODE REVIEW

**Comment by leofeyer** [comment]
I guess we have to add `--ingore-platform-reqs` for the PHP 8 test until the core-bundle is compatible as well.

**Comment by ausi** [comment]
Done.

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by ausi** [comment]
Should we release a new version?

**Comment by leofeyer** [comment]
Done.

**Pull request merged**
